### ISSUE TITLE
Dead link in "adversarial_inputs.md"

### ISSUE THREAD

**Issue by adomasbaliuka** [ammkrn/type_checking_in_lean4#5]
[This sentence](https://github.com/ammkrn/type_checking_in_lean4/blob/95d3ae55766f57621cc902c3de4f22222ff8ffdc/src/trust/adversarial_inputs.md?plain=1#L12) in the book:

> Note that there is nothing in principle preventing developers from writing software or extending a type checker to provide protection against such attacks, it's just not captured by the minimal functionality required by the kernel. However, the extent to which Lean's users have embraced its powerful custom syntax and macro systems may pose some challenges for those interested in improving the story here. Readers should consider this somewhat of an [open issue for future work](./future_work.md#improving-pollack-consistency)

has a hyperlink that is dead.

**Comment by ammkrn** [comment]
Thanks!
